# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/lenovo/sdm710-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter kunlun2 jd2019,$(TARGET_DEVICE)),)

endif
